// <auto-generated />
using MaxStore.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaxStore.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250806021313_Add F-Key")]
    partial class AddFKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MaxStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "မုန့်ဟင်းခါး၊ အုန်းနို့ခေါက်ဆွဲ၊ ရခိုင်မုန့်တီ နဲ့ အသုပ်အမျိုးမျိုး"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "ရှမ်းအစားအသောက်များ"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "ကော်ဖီ၊ လက်ဖက်ရည် နဲ့ လက်ဖက်ခြောက်"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "အသင့်စားစည်သွပ်ဘူးများ"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "အရံဟင်းလျာများ"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "လက်ဖက် နဲ့ အကြော်စုံ"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "ငါးပိ၊ ငါးခြောက် နဲ့ ပုဇွန်ခြောက်"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Medicine"
                        });
                });

            modelBuilder.Entity("MaxStore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("ListPrice")
                        .HasColumnType("double");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "a Description",
                            ListPrice = 4.0,
                            Title = "Product a"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "b Description",
                            ListPrice = 5.0,
                            Title = "Product b"
                        });
                });

            modelBuilder.Entity("MaxStore.Models.Product", b =>
                {
                    b.HasOne("MaxStore.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
