// <auto-generated />
using MaxStore.DataAccess;
using MaxStore.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaxStore.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MaxStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "မုန့်ဟင်းခါး၊ အုန်းနို့ခေါက်ဆွဲ၊ ရခိုင်မုန့်တီ နဲ့ အသုပ်အမျိုးမျိုး",
                            DisplayOrder = 1,
                            Name = "မုန့်ဟင်းခါး၊ အုန်းနို့ခေါက်ဆွဲ၊ ရခိုင်မုန့်တီ နဲ့ အသုပ်အမျိုးမျိုး"
                        },
                        new
                        {
                            Id = 2,
                            Description = "ရှမ်းအစားအသောက်များ",
                            DisplayOrder = 2,
                            Name = "ရှမ်းအစားအသောက်များ"
                        },
                        new
                        {
                            Id = 3,
                            Description = "ကော်ဖီ၊ လက်ဖက်ရည် နဲ့ လက်ဖက်ခြောက်",
                            DisplayOrder = 3,
                            Name = "ကော်ဖီ၊ လက်ဖက်ရည် နဲ့ လက်ဖက်ခြောက်"
                        },
                        new
                        {
                            Id = 4,
                            Description = "အသင့်စားစည်သွပ်ဘူးများ",
                            DisplayOrder = 4,
                            Name = "အသင့်စားစည်သွပ်ဘူးများ"
                        },
                        new
                        {
                            Id = 5,
                            Description = "အရံဟင်းလျာများ",
                            DisplayOrder = 5,
                            Name = "အရံဟင်းလျာများ"
                        },
                        new
                        {
                            Id = 6,
                            Description = "လက်ဖက် နဲ့ အကြော်စုံ",
                            DisplayOrder = 6,
                            Name = "လက်ဖက် နဲ့ အကြော်စုံ"
                        },
                        new
                        {
                            Id = 7,
                            Description = "ငါးပိ၊ ငါးခြောက် နဲ့ ပုဇွန်ခြောက်",
                            DisplayOrder = 7,
                            Name = "ငါးပိ၊ ငါးခြောက် နဲ့ ပုဇွန်ခြောက်"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Medicine",
                            DisplayOrder = 8,
                            Name = "Medicine"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
